#limitando a busca de arquivos .dart para buscar apenas em lib e gerar arquivos .g mais rapido
targets:
  $default:
    builders:
      mobx_codegen|mobx_generator:
        generate_for:
          - "lib/store/**.store.dart"